version: "3.0"
services: 
  apache:
    image: httpd:latest
    restart: always
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./htdocs:/usr/local/apache2/htdocs
    ports:
      - 80:80
 
  php:
    build: './myphp74'
    image: myphp74
    restart: always
    volumes_from:
      - apache

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./sqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Dumm!1234!
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql

